name: Metabedu
favicon: null
layout_spectrum: 0.50113
typography_spectrum: 0.4667399520985782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d3d3d3'
    - '#896c57'
    - '#843221'
    - '#e5481d'
  brandStrength: 0.625
  lightness: 0.9886262370273471
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
