name: Metabedu
favicon: null
layout_spectrum: 0.49707
typography_spectrum: 0.4667399520985782
title: 'Buddha and the Quantum Activist: Koans of Inner Peace Business and Connection'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#ababab'
    - '#3b7922'
    - '#c51420'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
