name: Metabedu
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4667399520985782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#afafaf'
    - '#4f4f4f'
    - '#870a0d'
  brandStrength: 0.5
  lightness: 0.9886262370273471
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
